name: carpcraft_app
description: Android-first mobile shell for CarpCraft Intelligence.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^12.0.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
